"""add full_name attr

Revision ID: 22b22cefcb5c
Revises: e731fb3c4678
Create Date: 2025-01-01 19:42:07.160789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "22b22cefcb5c"
down_revision: Union[str, None] = "e731fb3c4678"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "userrolepermission_user_id_fkey", "userrolepermission", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "userrolepermission", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userrolepermission", type_="foreignkey")
    op.create_foreign_key(
        "userrolepermission_user_id_fkey",
        "userrolepermission",
        "user",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
