"""fixed model relation

Revision ID: b67a0be3e729
Revises: 3079c74ae08a
Create Date: 2025-01-01 18:39:18.294241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b67a0be3e729"
down_revision: Union[str, None] = "3079c74ae08a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "full_name")
    op.drop_constraint(
        "userrolepermission_user_id_fkey", "userrolepermission", type_="foreignkey"
    )
    op.create_foreign_key(None, "userrolepermission", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userrolepermission", type_="foreignkey")
    op.create_foreign_key(
        "userrolepermission_user_id_fkey",
        "userrolepermission",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "user", sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
