"""add full_name attr

Revision ID: e731fb3c4678
Revises: 37697f98d973
Create Date: 2025-01-01 19:18:00.657371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e731fb3c4678"
down_revision: Union[str, None] = "37697f98d973"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "company_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.alter_column("user", "company_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
