"""add payment_provider column

Revision ID: b328ab851350
Revises: 3fa6c1cc135d
Create Date: 2025-01-03 17:54:59.383487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b328ab851350"
down_revision: Union[str, None] = "3fa6c1cc135d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "payment_provider",
            sa.Enum("FLUTTERWAVE", "PAYSTACK", name="paymentprovider"),
            nullable=False,
        ),
    )
    op.add_column(
        "order",
        sa.Column(
            "payment_type",
            sa.Enum("CARD", "CASH", "CHARGE_TO_ROOM", name="paymenttype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "payment_type")
    op.drop_column("order", "payment_provider")
    # ### end Alembic commands ###
