version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    command: fastapi dev
    image: user-api-image
    container_name: user-api-containet
